# Generated by Django 4.0.1 on 2022-02-27 16:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('food', models.IntegerField(default=0)),
                ('household_things', models.IntegerField(default=0)),
                ('transport', models.IntegerField(default=0)),
                ('medicine', models.IntegerField(default=0)),
                ('cloths', models.IntegerField(default=0)),
                ('guest', models.IntegerField(default=0)),
                ('utility', models.IntegerField(default=0)),
                ('other', models.IntegerField(default=0)),
                ('lunch', models.IntegerField(default=0)),
                ('entertainment', models.IntegerField(default=0)),
                ('care', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'spent',
            },
        ),
    ]
